### ISSUE TITLE
Drop place indicator doesn't match column drop place

### ISSUE THREAD

**Issue by kibiukibis** [patricktran/react-table-hoc-draggable-columns#1]
Hey @patricktran, thank you for this hoc. Helped a lot. But there is minor issue with drop and drop indicator mismatch on reorder mode. 
When dropping on first half of column indicator shows that it will be dropped before the column, but is dropped after column.

**Comment by patricktran** [comment]
Hmmm, I'm not seeing this behavior.  Are you able to consistently reproduce on the demo page or do you have a codesandbox.io example?

**Comment by kibiukibis** [comment]
Yes I am able on demo page. Let's say drag "Vin" column in the beginning of "Brand" column. Arrow appears before "Brand" column, but "Vin" is dropped after "Brand" column.

**Comment by patricktran** [comment]
#479f821

Thanks for reporting this!  Fixed in v 1.0.1

Please let me know if you encounter any other issues.
