### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by Teipo** [patricktran/react-table-hoc-draggable-columns#14]
Hi

1.  I am receiving an uncaught type error.

![image](https://user-images.githubusercontent.com/25818235/80209088-4bb29f80-8629-11ea-94a5-41dae6e164f4.png)

2. I am also getting a memory leak error
![image](https://user-images.githubusercontent.com/25818235/80209134-65ec7d80-8629-11ea-9932-433d5d7556a0.png)

3. I think some logging is active: 
![image](https://user-images.githubusercontent.com/25818235/80209229-9502ef00-8629-11ea-85a2-0f86b7081420.png)

**Comment by patricktran** [comment]
Yes, I unfortunately left a couple of console.logs in by mistake.  These will be removed in the next update.

Regarding your uncaught type error, can you please provide sample code or an example on codesandbox?

**Comment by Teipo** [comment]
Hi Patrick,

I had some issues when updating the order of columns in react-table via the function 'onDropSuccess', I tried setting my custom component state again and resetting the columns in react-table, basically re-rendering the table, and that's when the error occurred, even though the order and render was fine, I still got the error message.

I removed the setState({columns}) in my custom component when 'onDropSuccess' is called and the column order changed, and did not re-render the react-table component, then it works fine :)

So the error indeed was on my end.
