### ISSUE TITLE
react-table-hoc-draggable-columns not working in IE 11 and mobile devices

### ISSUE THREAD

**Issue by hegdesudheer007** [patricktran/react-table-hoc-draggable-columns#18]
react-table-hoc-draggable-columns not working IE11 or older versions and also for mobile browsers.
![drag_and_drop_ie_error](https://user-images.githubusercontent.com/44539198/91901342-b5b91080-ecbd-11ea-96dc-8f79092f8d62.PNG)

Any workaround for this issue on IE and Mobile browsers?

**Comment by patricktran** [comment]
Sorry, we are not supporting IE11 as it will require too many polyfills to support missing Javascript functionality that are now part of the Javascript standard.
