### ISSUE TITLE
draggable-columns not supported for some V6 versions

### ISSUE THREAD

**Issue by Yasith91** [patricktran/react-table-hoc-draggable-columns#23]
Go to this sand box and try with default version (V 6.7.0)
https://codesandbox.io/s/xo4w7l3rlz
It's working perfectly fine. Now change react-table version in to (V 6.11.5 or V 6.10.2 or some version above this.)
with these versions drag table is not working accordingly.

**Comment by patricktran** [comment]
Hi @Yasith91, is there a particular reason why you need to use version 6.11.5 or 6.10.2?  

If you are using ReactTableV6, it is now recommended for you to use: **npm install react-table-v6**  (6.8.6)
https://www.npmjs.com/package/react-table-v6 

Here is a working code sandbox using the react-table-v6 package.
https://codesandbox.io/s/fast-sea-hd78k?file=/src/App.js
