### ISSUE TITLE
Can't reorder columns then some columns hidden.

### ISSUE THREAD

**Issue by NikolaevRoman** [patricktran/react-table-hoc-draggable-columns#8]
Hi, I got error. I can't normally drag'n'drop columns then some columns hidden. 
- react-table-hoc-draggable-columns version 1.2.2
- react-table version 6.10.3
Example: https://codesandbox.io/s/adoring-minsky-r23rw?fontsize=14&hidenavigation=1&theme=dark

**Comment by patricktran** [comment]
Hi @NikolaevRoman 

You forgot to include the custom css:
import 'react-table-hoc-draggable-columns/dist/styles.css';

Here is a forked example:  https://codesandbox.io/s/stoic-cloud-6izj9

**Comment by NikolaevRoman** [comment]
I saw your example.
But if I set prop "show:false" for any column, I can't drag'n'drop columns normally.
Example based on your's: https://codesandbox.io/s/stoic-cloud-6izj9?fontsize=14&hidenavigation=1&theme=dark

Demonstration:
![2020-04-07-09-39-13](https://user-images.githubusercontent.com/4966993/78637776-bc309100-78b3-11ea-9b9f-b132d0b8b424.gif)

**Comment by patricktran** [comment]
@NikolaevRoman   Thanks, I will look into this issue

**Comment by patricktran** [comment]
@NikolaevRoman Updated the package. Please try with version 1.2.3

**Comment by NikolaevRoman** [comment]
Hi, @patricktran 
Check version 1.2.3. All work fine. 
Thanks.
